[package]
name = "gdpm-downloader"
version = "1.1.1"
edition = "2021"

[dependencies]
futures-util = "0.3.17"
indicatif = "0.16.2"
reqwest = { version = "0.11.6", features = ["stream"] }
thiserror = "1.0.30"
tokio = { version = "1.13.0", features = ["rt"] }
