[package]
name = "gdpm-downloader"
version = "1.2.0"
edition = "2021"

[dependencies]
async-recursion = "1.0.0"
async-trait = "0.1.53"
futures-util = "0.3.17"
indicatif = "0.16.2"
indoc = "1.0.6"
mockall = "0.11.1"
reqwest = { version = "0.11.6", features = ["stream"] }
soup = "0.5.1"
thiserror = "1.0.30"
tokio = { version = "1.18", features = ["rt", "macros"] }
gdsettings-parser = { path = "../gdsettings-parser" }
gdpm-types = { path = "../gdpm-types" }
tracing = "0.1.34"

[dev-dependencies]
pretty_assertions = "1.2.1"
