[package]
name = "gdpm-downloader"
version = "1.3.0-rc1"
edition = "2021"

[dependencies]
async-recursion = "1.0.0"
async-trait = "0.1.56"
futures-util = "0.3.21"
indicatif = "0.16.2"
indoc = "1.0.6"
mockall = "0.11.2"
reqwest = { version = "0.11.11", features = ["stream"] }
soup = "0.5.1"
thiserror = "1.0.31"
tokio = { version = "1.20.1", features = ["rt", "macros"] }
gdsettings-parser = { path = "../gdsettings-parser" }
gdpm-types = { path = "../gdpm-types" }
tracing = "0.1.35"

[dev-dependencies]
pretty_assertions = "1.2.1"
