[workspace]
members = [
    "crates/gdpm-downloader",
    "crates/gdpm-cli",
    "crates/gdpm-core",
    "crates/gdpm-io",
    "crates/gdpm-macros",
    "crates/gdpm-types",
    "crates/gdscript-parser",
    "crates/gdsettings-parser",
]

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
debug = 1