[package]
name = "gdpm-io"
version = "1.3.0-rc1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
dirs = "4.0.0"
fs_extra = "1.2.0"
mockall = "0.11.2"
remove_dir_all = "0.7.0"
thiserror = "1.0.31"
tracing = "0.1.35"
zip = "0.6.2"
