[package]
name = "gdpm-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdsettings-parser = { path = "../gdsettings-parser" }
thiserror = "1.0.30"
