name: Checks

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/prepare
    - run: just fmt-check

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/prepare
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: lint-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: just lint-err

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/prepare
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: test-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions-rs/tarpaulin@v0.1
      with:
        args: '-- --test-threads 1'
        out-type: Lcov
    - uses: coverallsapp/github-action@master
      with:
        path-to-lcov: lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/prepare
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: build-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: just build
